### ISSUE TITLE
Blacklist Hashes for Public trackers

### ISSUE THREAD

**Issue by iBringit** [chihaya/chihaya#81] opened 2015-07-24 06:19 UTC
Add option to blacklist hex or hashes that operators doesn't want to track.

Eg.. 
1. Someone sends a DMCA regarding a hash to be blocked.
2. Someone uploads a fake material and you want to block that hash.

This will be great to have as most trackers go down just because of a single or two or more hashes they are unable to block.

**Comment by dtrackd** [comment] 2015-07-24 07:36
Dupe of issue #79

**Closed** 2015-07-24 14:01 UTC
