### ISSUE TITLE
JSON 'flattened' Memory stats not 'flat'

### ISSUE THREAD

**Issue by cooperlees** [chihaya/chihaya#137] opened 2016-03-07 04:06 UTC
Getting a "": key for memory statistics and they have not been flattened at all.
pastebin of output from a curl (curl http://localhost:6968/stats?flatten=1 | json_pretty): http://pastebin.com/Mww37CY7

**Comment by jzelinskie** [comment] 2016-03-08 03:34
Was this always the case? what version did you upgrade from that handled this correctly? I don't think we've touched stats in a long time, so it might be a dependency.

**Comment by cooperlees** [comment] 2016-03-09 01:12
Here is what I get from production trackers:
http://pastebin.com/bytwqa0c

So this is definitely not always the case :D

**Comment by jzelinskie** [comment] 2016-04-02 19:13
@cooperlees did you ever resolve this? @pushrax and I couldn't reproduce.

**Comment by jzelinskie** [comment] 2016-09-03 20:14
Closing this since we couldn't reproduce and the v2.0.0 will use Prometheus.

**Closed by jzelinskie** 2016-09-03 20:14 UTC
Labels: kind/bug
