### ISSUE TITLE
bittorrent 7.10.4  [bad connection ID]

### ISSUE THREAD

**Issue by f4nff** [chihaya/chihaya#422] opened 2018-09-17 12:42 UTC
![image](https://user-images.githubusercontent.com/19538878/45623501-1f808580-baba-11e8-8066-0498b18d96b7.png)

**Comment by f4nff** [comment] 2018-09-17 12:44
Why is there no such problem with opentracker?

**Comment by mrd0ll4r** [comment] 2018-09-17 13:01
I am going to quote this from my earlier reply:

The bittorrent [spec](http://bittorrent.org/beps/bep_0015.html) says

> A client can use a connection ID until one minute after it has received it. Trackers should accept the connection ID until two minutes after it has been sen[t].

Please note, last time I checked, **opentracker does not implement the spec correctly**. It will accept a connection ID for up to an hour, or even two in some cases. You can see this in `ot_udp.c`, the function `udp_make_connectionid`.

If you can send me the debug logs again, I can confirm whether this is a bug in the client. My guess would be yes, because afaik uTorrent and BitTorrent mainline share a lot of their codebase.

**Comment by mrd0ll4r** [comment] 2018-09-21 11:05
Closing this in favor of #417 because that has more info

**Closed by mrd0ll4r** 2018-09-21 11:05 UTC
