### ISSUE TITLE
IncrementTorrentSnatches not working correctly?

### ISSUE THREAD

**Issue by Yuuki2012** [chihaya/chihaya#127] opened 2016-01-04 15:42 UTC
As the title says, it doesn't work? I'm trying to scrape but it's ALWAYS returning 0
( Example: https://yuuki-chan.xyz/scraper/ )

**Comment by mrd0ll4r** [comment] 2016-01-04 16:14
What exactly are you doing before scraping? And what is the format for the scrape you posted? How do you get the data? (API or real scrape?)

**Comment by Yuuki2012** [comment] 2016-01-04 17:10
I'm using the http://website.tld:6881/scrape?info_hash=HASH_GOES_HERE
the API isn't working for me either, or I have no idea how that works.\

it's written in PHP, I'm using https://github.com/johannes85/PHP-Torrent-Scraper

**Comment by mrd0ll4r** [comment] 2016-01-04 19:36
I cannot reproduce *your* issue, but I've found a another one. Anyways, this is what I've done:

1. hit `http://<tracker>/announce?info_hash=0000000000000000&peer_id=0000000000000000&port=20222&left=1&downloaded=0&uploaded=0` - this adds you to the leechers for that torrent
2. hit `http://<tracker>/announce?info_hash=0000000000000000&peer_id=0000000000000000&port=20222&left=0&downloaded=0&uploaded=0&event=completed` - this removes you from the leechers, adds you to the seeders and _should_ increment the snatches by one
3. hit http://<tracker>/scrape?info_hash=0000000000000000 - you'll get something like

        d5:filesd16:0000000000000000d8:completei1e10:incompletei0e10:downloadedi2eeee

Notice how downloaded is `2`? That should be `1` AFAIK

The bug is in [tracker/announce.go:200](https://github.com/chihaya/chihaya/blob/master/tracker/announce.go#L200) - we use the `&*val` construct to get the torrent for the announce, but it seems like that doesn't work properly (and we increment the snatches on the original torrent (without synchronization!)). It works if you comment that line out.
This is also a problem of our spaghetti-like code to create the announce object to work with. We're working to redesign the internals, so that should probably be fixed as well.

@jzelinskie please re-test if you have time/fix in your local branch - We should add a test for that somewhere, but I don't think a PR makes sense right now?

**Comment by jzelinskie** [comment] 2016-01-04 20:35
It looks like something in the Go runtime changed and the `*&var` trick no longer makes a copy! See http://play.golang.org/p/PEC7sJ9lLm

I'd be willing to accept a PR removing the local increment for now. But this is a pretty big deal. I'm going to push my refactor branch soon, so that we can accelerate that work. Thanks for waiting patiently for my sharing of that code @mrd0ll4r.

**Comment by pushrax** [comment] 2016-01-04 20:42
When did that happen... that's good to know. This still works though: http://play.golang.org/p/B5yDABUUcW

**Comment by jzelinskie** [comment] 2016-01-04 21:34
This should be fixed in f70be949118a1ed9136224b3a618d95362b24d65. Let me know that it works and I'll close the issue.

**Comment by Yuuki2012** [comment] 2016-01-05 15:25
@mrd0ll4r I tried those urls, seems to work, but shouldn't the torrent clients tell the tracker it's completed downloading? (I'm using qBittorrent and libTorrent (ruTorrent)), but neither of them return to the tracker that they've finished downloading.

**Comment by mrd0ll4r** [comment] 2016-01-05 16:11
@jzelinskie fixed it for me, thx :)

@Yuuki2012 they should indeed. I'll test it with libTorrent...

**Comment by Yuuki2012** [comment] 2016-01-06 11:49
@mrd0ll4r did you figure anything out?

**Comment by mrd0ll4r** [comment] 2016-01-06 13:35
I don't have a second machine to seed from right now, so I can't test it too well - I did test it for a public torrent where I just added an instance of chihaya to the list of trackers (as the primary tracker, actually). libTorrent did interact with it, but didn't report a download. I had the debug log on, so I saw all requests made to chihaya, and none contained `event=completed`.

Can you maybe check how this works with a torrent marked "private"? As I said, I can't test that right now because I can't seed

**Comment by Yuuki2012** [comment] 2016-01-11 12:52
@mrd0ll4r https://yuuki-chan.xyz/torrents.php < as you can see the download counter works here, it's not marked as private torrent tho, but I think it's a client problem, that not all clients pass "event=completed" to the tracker.

**Comment by mrd0ll4r** [comment] 2016-01-11 15:13
@Yuuki2012 yes, I got the same impression. Thanks for reporting the issue :)

@jzelinskie fixed, close?

**Comment by jzelinskie** [comment] 2016-01-21 20:31
This should be fixed. Let me know if it isn't and I'll reopen.

**Closed by jzelinskie** 2016-01-21 20:31 UTC
Labels: bug
